### PR TITLE
Added `JSTagsCollection.onAdd` and `JSTagsCollection.onRemove` methods t...

### PR DESCRIPTION
**Pull request by yjaaidi**
Added `JSTagsCollection.onAdd` and `JSTagsCollection.onRemove` methods to inject callbacks when tag is added or removed.
This is useful in order to modify the typeahead suggestions for example or display an alert etc... instead of adding an extra watcher to the tags list which is performance expensive and needs extra code to know if an item was added or removed.

### CODE REVIEW

**Comment by eranhirs** [comment]
Looking good!
Just change version to 0.3.5

**Comment by yjaaidi** [comment]
OK! Thanks!

So I'll add two pull requests as 0.3.4.1 and 0.3.4.2 for my two last pull
requests and a 0.3.5 for this one. OK ?

**Comment by eranhirs** [comment]
Yes modify the same pull requests

**Comment by eranhirs** [comment]
Already merged with #17

**Comment by eranhirs** [comment]
Please rebase both PR

**Comment by eranhirs** [comment]
Ok everything is merged, keep up the good job!

**Comment by yjaaidi** [comment]
Thanks! And thank for the great job you did with this module ;).
It will be soon visible on https://www.wishtack.com ;)

**Pull request merged**
