### PR TITLE
BUGFIX: Fixed active tag selection when using uneditable typeahead by ha...

### PR DESCRIPTION
**Pull request by yjaaidi**
Fixes active tag selection when using uneditable typeahead which was broken because 'inputService.input' is set to undefined and does not pass the 'inputService.input === ""' test.

### CODE REVIEW

**Comment by eranhirs** [comment]
Please avoid using ==

**Comment by yjaaidi** [comment]
Hi Eran,

Sorry for that, but the only case where I allow myself to use '==' is to
compare to 'null' in order to avoid comparing to 'undefined' and 'null'.

Do you prefer this form: (value !== undefined) && (value !== null) ?

Thanks in advance.

**Comment by eranhirs** [comment]
For example I'm not sure what happens if someone inputs 0 or [], better not use it.
Are you sure both of the conditions are needed? If yes then go ahead with the latter

Also update version in bower.json and package.json

Thanks!

**Comment by eranhirs** [comment]
For example I'm not sure what happens if someone inputs 0 or [], better not use it.
Are you sure both of the conditions are needed? If yes then go ahead with the latter

Also update version in bower.json and package.json

Thanks!

**Comment by eranhirs** [comment]
For example I'm not sure what happens if someone inputs 0 or [], better not use it.
Are you sure both of the conditions are needed? If yes then go ahead with the latter

Also update version in bower.json and package.json

Thanks!

**Comment by yjaaidi** [comment]
Having 0 or [] as an input should never happen as the value will always be
undefined or a string or an object given to the typeahead datasets.

But even if it happens as a developer might controller the model value, 0
and [] don't match the '== null' test. '== null' only matches null and
undefined.

OK. I'm bumping the version and replacing '== null' by '=== null or ===
 undefined'.

Thank you for your fast reply.

**Comment by yjaaidi** [comment]
Done!

By the way, shouldn't we name this version 0.3.5 and the one with the onAdd/onRemove 0.4.0 as it's an interface change?

**Comment by yjaaidi** [comment]
In reply to:
    Editable cancels the option to edit an existing tag.
    This is different from custom tags, please explain this change.

The problem I'm fixing here is that when typeahead is enabled and is not in editable mode, if user presses an exit code button like enter button, this will erase the input without producing any other effect because when typeahead is not in editable mode, only the values given as suggestions are accepted, all custom values are rejected.
So, I'm not talking about jsTag's "edit" option but typeahead's "editable" option.
The behaviour I'm expecting and that most people are probably expecting is that if typeahead is not in editable mode and I'm entering an input that doesn't match any suggestion and then I press enter, then  nothing should happen.

**Comment by yjaaidi** [comment]
I just noticed that "options.$event" was already copied into a variable named "e". This is the ng-keydown event. When pressing enter to add a tag, the event must not trigger form's ng-submit. The enter button triggers the form submit only if the input is empty.
Thus, when a user enters a value in the input, pressing enter for the first time will add the tag and empty the input, pressing enter a second time will then submit the form.

**Comment by yjaaidi** [comment]
Well, I noticed that jquery was used in jsTagTypeahead so I allowed myself to use it. Sorry for that.
I replaced it by "angular.element". I also added the following explanation in code comments.

    // In order to know how to handle a breakCode or a backspace, we must know if the typeahead
    // input value is empty or not. e.g. if user hits backspace and typeahead input is not empty
    // then we have nothing to do as user is not trying to remove a tag but simply tries to
    // delete some character in typeahead's input.
    // To know the value in the typeahead input, we can't use `this.input` because when
    // typeahead is in uneditable mode, the model (i.e. `this.input`) is not updated and is set
    // to undefined. So we have to fetch the value directly from the typeahead input element.

I also fixed a probable bug (0.3.4.5) when retrieving input value as I assumed that typeahead was always enabled but it's obviously not the case :).

Tell me when you're ok with this pull request so I can rebase other pull requests and bump versions.

**Comment by eranhirs** [comment]
Ok everything looks good! Thank you for changing and explaining.
When you finish I will merge this pull request and close the others.

**Comment by yjaaidi** [comment]
You're welcome :)

**Comment by yjaaidi** [comment]
Thanks !

**Pull request merged**
